# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/das-bdd
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: das-password
      POSTGRES_DB: das-bdd
